"""Add RAG models

Revision ID: 47de4800334b
Revises: 
Create Date: 2026-06-14 12:42:39.809154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '47de4800334b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_chat_id'), 'documents', ['chat_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.drop_table('_prisma_migrations')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('chats', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chats', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chats', 'model_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('chats', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'New chat'::text"))
    op.drop_constraint(op.f('chats_model_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'models', ['model_id'], ['id'], ondelete='SET NULL')
    op.alter_column('installations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('installations', 'server_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('installations', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('installations', 'status',
               existing_type=postgresql.ENUM('QUEUED', 'PULLING', 'VERIFYING', 'COMPLETED', 'FAILED', 'CANCELLED', name='InstallStatus'),
               type_=sa.Enum('QUEUED', 'PULLING', 'VERIFYING', 'COMPLETED', 'FAILED', 'CANCELLED', name='installstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('installations', 'error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('installations_server_id_fkey'), 'installations', type_='foreignkey')
    op.create_foreign_key(None, 'installations', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='MessageRole'),
               type_=sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False),
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.alter_column('models', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('models', 'server_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('models', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('models', 'family',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('models', 'digest',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('models', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('models_server_id_idx'), table_name='models')
    op.drop_index(op.f('models_server_id_name_key'), table_name='models')
    op.create_unique_constraint('models_server_id_name_key', 'models', ['server_id', 'name'])
    op.create_index(op.f('ix_models_server_id'), 'models', ['server_id'], unique=False)
    op.drop_constraint(op.f('models_server_id_fkey'), 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('refresh_tokens_token_hash_key'), table_name='refresh_tokens')
    op.drop_index(op.f('refresh_tokens_user_id_idx'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('servers', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('servers', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('servers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('servers', 'host',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('servers', 'provider',
               existing_type=postgresql.ENUM('OLLAMA', 'LM_STUDIO', 'VLLM', 'OPENAI_COMPAT', 'LOCALAI', name='Provider'),
               type_=sa.Enum('OLLAMA', 'LM_STUDIO', 'VLLM', 'OPENAI_COMPAT', 'LOCALAI', name='provider', native_enum=False),
               existing_nullable=False)
    op.alter_column('servers', 'api_key_cipher',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('servers', 'api_key_iv',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('servers', 'api_key_tag',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('servers', 'status',
               existing_type=postgresql.ENUM('ONLINE', 'OFFLINE', 'UNKNOWN', 'ERROR', name='ServerStatus'),
               type_=sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', 'ERROR', name='serverstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'UNKNOWN\'::"ServerStatus"'))
    op.alter_column('servers', 'version',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('servers_user_id_name_key'), table_name='servers')
    op.create_unique_constraint('servers_user_id_name_key', 'servers', ['user_id', 'name'])
    op.drop_constraint(op.f('servers_user_id_fkey'), 'servers', type_='foreignkey')
    op.create_foreign_key(None, 'servers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_settings', 'theme',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::text"))
    op.alter_column('user_settings', 'default_model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_settings', 'locale',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('user_settings', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='Role'),
               type_=sa.Enum('USER', 'ADMIN', name='role', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'USER\'::"Role"'))
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_index(op.f('users_email_key'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('workspace_members', 'workspace_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workspace_members', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workspace_members', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', name='WorkspaceRole'),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='workspacerole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'MEMBER\'::"WorkspaceRole"'))
    op.drop_constraint(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('workspace_members_user_id_fkey'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workspaces', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workspaces', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_members_user_id_fkey'), 'workspace_members', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', 'workspaces', ['workspace_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('workspace_members', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='workspacerole', native_enum=False),
               type_=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', name='WorkspaceRole'),
               existing_nullable=False,
               existing_server_default=sa.text('\'MEMBER\'::"WorkspaceRole"'))
    op.alter_column('workspace_members', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('workspace_members', 'workspace_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('users_email_key'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='role', native_enum=False),
               type_=postgresql.ENUM('USER', 'ADMIN', name='Role'),
               existing_nullable=False,
               existing_server_default=sa.text('\'USER\'::"Role"'))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('user_settings', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_settings', 'locale',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('user_settings', 'default_model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_settings', 'theme',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::text"))
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.create_foreign_key(op.f('servers_user_id_fkey'), 'servers', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('servers_user_id_name_key', 'servers', type_='unique')
    op.create_index(op.f('servers_user_id_name_key'), 'servers', ['user_id', 'name'], unique=True)
    op.alter_column('servers', 'version',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'status',
               existing_type=sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', 'ERROR', name='serverstatus', native_enum=False),
               type_=postgresql.ENUM('ONLINE', 'OFFLINE', 'UNKNOWN', 'ERROR', name='ServerStatus'),
               existing_nullable=False,
               existing_server_default=sa.text('\'UNKNOWN\'::"ServerStatus"'))
    op.alter_column('servers', 'api_key_tag',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'api_key_iv',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'api_key_cipher',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'provider',
               existing_type=sa.Enum('OLLAMA', 'LM_STUDIO', 'VLLM', 'OPENAI_COMPAT', 'LOCALAI', name='provider', native_enum=False),
               type_=postgresql.ENUM('OLLAMA', 'LM_STUDIO', 'VLLM', 'OPENAI_COMPAT', 'LOCALAI', name='Provider'),
               existing_nullable=False)
    op.alter_column('servers', 'host',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('servers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('servers', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('servers', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('refresh_tokens_user_id_idx'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], unique=True)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('notifications', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key(op.f('models_server_id_fkey'), 'models', 'servers', ['server_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_models_server_id'), table_name='models')
    op.drop_constraint('models_server_id_name_key', 'models', type_='unique')
    op.create_index(op.f('models_server_id_name_key'), 'models', ['server_id', 'name'], unique=True)
    op.create_index(op.f('models_server_id_idx'), 'models', ['server_id'], unique=False)
    op.alter_column('models', 'parameters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('models', 'digest',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('models', 'family',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('models', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('models', 'server_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('models', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.alter_column('messages', 'model_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False),
               type_=postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='MessageRole'),
               existing_nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'installations', type_='foreignkey')
    op.create_foreign_key(op.f('installations_server_id_fkey'), 'installations', 'servers', ['server_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('installations', 'error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('installations', 'status',
               existing_type=sa.Enum('QUEUED', 'PULLING', 'VERIFYING', 'COMPLETED', 'FAILED', 'CANCELLED', name='installstatus', native_enum=False),
               type_=postgresql.ENUM('QUEUED', 'PULLING', 'VERIFYING', 'COMPLETED', 'FAILED', 'CANCELLED', name='InstallStatus'),
               existing_nullable=False)
    op.alter_column('installations', 'model_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('installations', 'server_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('installations', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('chats_model_id_fkey'), 'chats', 'models', ['model_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('chats', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'New chat'::text"))
    op.alter_column('chats', 'model_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chats', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chats', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_chat_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
